server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  datasource:
    #postgresql://containers-us-west-72.railway.app:6428/railway
    url: jdbc:postgresql://containers-us-west-72.railway.app:6428/railway
    username: postgres
    password: H6CoSwgZsSQBHSXG3tbf
  liquibase:
    change-log: classpath:db/changelog/db-changelog.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    #        show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  data:
    rest:
      base-path: "/api/v2"
      detection-strategy: annotated
  web:
    resources:
      static-locations:
        - file:src/main/resources/order-photos

springdoc:
  swagger-ui:
    path: /swagger-ui
